# Generated by Django 2.2.1 on 2019-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(),
        ),
    ]
